package generator

import (
	"net/http"
	"sort"
)

// generatedFileHeader is written at the top of every generated file, so
// it is unmistakable that the file should not be hand-edited.
const generatedFileHeader = "// Code generated by mailwizz-cli-gen from openapi/schema.json. DO NOT EDIT.\n\n"

// RenderAPIClient returns the source of internal/generated/api/client_gen.go:
// the Client type that wraps apiclient.Client with the generated
// operations in RenderAPIOperations.
func RenderAPIClient() string {
	var out codeWriter

	out.writeString(generatedFileHeader)
	out.writeString("package api\n\n")
	out.writeString("import \"github.com/onetwist-software/mailwizz-cli/internal/apiclient\"\n\n")
	out.writeString("// Client wraps the low level HTTP client with one typed method per\n")
	out.writeString("// MailWizz API operation; see operations_gen.go.\n")
	out.writeString("type Client struct {\n\t*apiclient.Client\n}\n\n")
	out.writeString("// NewClient wraps base, adding the generated MailWizz API operations.\n")
	out.writeString("func NewClient(base *apiclient.Client) *Client {\n")
	out.writeString("\treturn &Client{Client: base}\n")
	out.writeString("}\n")

	return out.String()
}

// RenderAPIOperations returns the source of
// internal/generated/api/operations_gen.go: one Request struct and one
// Client method per operation, sorted by OperationID for stable output
// across regenerations.
func RenderAPIOperations(operations []*Operation) string {
	sorted := sortedByOperationID(operations)

	var out codeWriter

	out.writeString(generatedFileHeader)
	out.writeString("package api\n\n")
	out.writeString("import (\n\t\"context\"\n\t\"net/url\"\n\n")
	out.writeString("\t\"github.com/onetwist-software/mailwizz-cli/internal/apiclient\"\n)\n")

	for _, operation := range sorted {
		out.writeString("\n")
		renderRequestStruct(&out, operation)
		out.writeString("\n")
		renderClientMethod(&out, operation)
	}

	return out.String()
}

func sortedByOperationID(operations []*Operation) []*Operation {
	sorted := make([]*Operation, len(operations))
	copy(sorted, operations)

	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].OperationID < sorted[j].OperationID
	})

	return sorted
}

func renderRequestStruct(out *codeWriter, operation *Operation) {
	out.printf("// %sRequest is the request payload for %s %s.\n",
		operation.GoName, operation.Method, operation.Path)
	out.printf("type %sRequest struct {\n", operation.GoName)

	for _, field := range operation.RequestFields() {
		if field.Description != "" {
			out.printf("\t// %s\n", field.Description)
		}

		out.printf("\t%s string\n", field.GoField)
	}

	out.writeString("}\n")
}

func renderClientMethod(out *codeWriter, operation *Operation) {
	out.printf("// %s calls %s %s.\n", operation.GoName, operation.Method, operation.Path)

	if operation.Summary != "" {
		out.printf("//\n// %s\n", operation.Summary)
	}

	out.printf("func (c *Client) %s(ctx context.Context, req %sRequest) (*apiclient.Response, error) {\n",
		operation.GoName, operation.GoName)
	out.printf("\tpath := %s\n", operation.PathExpr())

	switch operation.Method {
	case http.MethodGet:
		renderGet(out, operation)
	case http.MethodDelete:
		out.writeString("\treturn c.Delete(ctx, path)\n")
	default:
		renderFormCall(out, operation)
	}

	out.writeString("}\n")
}

func renderGet(out *codeWriter, operation *Operation) {
	if len(operation.QueryParams) == 0 {
		out.writeString("\treturn c.Get(ctx, path, nil)\n")

		return
	}

	out.writeString("\tquery := url.Values{}\n")

	for _, p := range operation.QueryParams {
		out.printf("\tif req.%s != \"\" {\n\t\tquery.Set(%q, req.%s)\n\t}\n", p.GoField, p.Name, p.GoField)
	}

	out.writeString("\treturn c.Get(ctx, path, query)\n")
}

func renderFormCall(out *codeWriter, operation *Operation) {
	method := "PostForm"
	if operation.Method == http.MethodPut {
		method = "PutForm"
	}

	if len(operation.BodyFields) == 0 {
		out.printf("\treturn c.%s(ctx, path, url.Values{})\n", method)

		return
	}

	out.writeString("\tform := url.Values{}\n")

	for _, field := range operation.BodyFields {
		out.printf("\tif req.%s != \"\" {\n\t\tform.Set(%q, req.%s)\n\t}\n",
			field.GoField, field.FormKey, field.GoField)
	}

	out.printf("\treturn c.%s(ctx, path, form)\n", method)
}
