// Code generated by mailwizz-cli-gen from openapi/schema.json. DO NOT EDIT.

package api

import "github.com/onetwist-software/mailwizz-cli/internal/apiclient"

// Client wraps the low level HTTP client with one typed method per
// MailWizz API operation; see operations_gen.go.
type Client struct {
	*apiclient.Client
}

// NewClient wraps base, adding the generated MailWizz API operations.
func NewClient(base *apiclient.Client) *Client {
	return &Client{Client: base}
}
