// Code generated by mailwizz-cli-gen from openapi/schema.json. DO NOT EDIT.

package api

import (
	"context"
	"net/url"

	"github.com/onetwist-software/mailwizz-cli/internal/apiclient"
)

// ActivateWidgetRequest is the request payload for PUT /widgets/{widget_id}/activate.
type ActivateWidgetRequest struct {
	// Unique id of the widget
	WidgetID string
}

// ActivateWidget calls PUT /widgets/{widget_id}/activate.
//
// Activate widget
func (c *Client) ActivateWidget(ctx context.Context, req ActivateWidgetRequest) (*apiclient.Response, error) {
	path := "/widgets/" + url.PathEscape(req.WidgetID) + "/activate"
	return c.PutForm(ctx, path, url.Values{})
}

// CreateWidgetRequest is the request payload for POST /widgets.
type CreateWidgetRequest struct {
	// The color of the widget
	GeneralColor string
	// The name of the widget
	GeneralName string
}

// CreateWidget calls POST /widgets.
//
// Create widget
func (c *Client) CreateWidget(ctx context.Context, req CreateWidgetRequest) (*apiclient.Response, error) {
	path := "/widgets"
	form := url.Values{}
	if req.GeneralColor != "" {
		form.Set("general[color]", req.GeneralColor)
	}
	if req.GeneralName != "" {
		form.Set("general[name]", req.GeneralName)
	}
	return c.PostForm(ctx, path, form)
}

// ViewWidgetRequest is the request payload for GET /widgets/{widget_id}.
type ViewWidgetRequest struct {
	// Unique id of the widget
	WidgetID string
}

// ViewWidget calls GET /widgets/{widget_id}.
//
// View widget
func (c *Client) ViewWidget(ctx context.Context, req ViewWidgetRequest) (*apiclient.Response, error) {
	path := "/widgets/" + url.PathEscape(req.WidgetID)
	return c.Get(ctx, path, nil)
}

// ViewWidgetsRequest is the request payload for GET /widgets.
type ViewWidgetsRequest struct {
	// Filter by status
	Status string
	// Page number to fetch, starting at 1.
	Page string
}

// ViewWidgets calls GET /widgets.
//
// View widgets
func (c *Client) ViewWidgets(ctx context.Context, req ViewWidgetsRequest) (*apiclient.Response, error) {
	path := "/widgets"
	query := url.Values{}
	if req.Status != "" {
		query.Set("status", req.Status)
	}
	if req.Page != "" {
		query.Set("page", req.Page)
	}
	return c.Get(ctx, path, query)
}
