// Code generated by mailwizz-cli-gen from openapi/schema.json. DO NOT EDIT.

package cli

import (
	"context"
	"fmt"

	"github.com/urfave/cli/v3"

	"github.com/onetwist-software/mailwizz-cli/internal/commands"
	"github.com/onetwist-software/mailwizz-cli/internal/generated/api"
	"github.com/onetwist-software/mailwizz-cli/internal/output"
)

// Commands returns every top-level MailWizz API command, generated from
// openapi/schema.json.
func Commands() []*cli.Command {
	return []*cli.Command{
		widgetsCommand(),
	}
}

// widgetsCommand returns the "widgets" command.
func widgetsCommand() *cli.Command {
	return &cli.Command{
		Name:  "widgets",
		Usage: "Manage widgets",
		Commands: []*cli.Command{
			widgetsListCommand(),
			widgetsViewCommand(),
			widgetsCreateCommand(),
			widgetsActivateCommand(),
		},
	}
}

// widgetsListCommand returns the "list" command.
func widgetsListCommand() *cli.Command {
	return &cli.Command{
		Name:  "list",
		Usage: "View widgets",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "status",
				Usage: "Filter by status (allowed values: active, inactive)",
				Validator: func(v string) error {
					switch v {
					case "", "active", "inactive":
						return nil
					default:
						return fmt.Errorf("%s", "status must be one of: active, inactive")
					}
				},
			},
			&cli.StringFlag{
				Name:  "page",
				Usage: "Page number to fetch, starting at 1.",
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := commands.ResolveClient()
			if err != nil {
				return err
			}

			req := api.ViewWidgetsRequest{
				Status: cmd.String("status"),
				Page:   cmd.String("page"),
			}

			resp, err := client.ViewWidgets(ctx, req)
			if err != nil {
				return fmt.Errorf("viewWidgets: %w", err)
			}

			return output.Handle(cmd.Root().Writer, resp)
		},
	}
}

// widgetsViewCommand returns the "view" command.
func widgetsViewCommand() *cli.Command {
	return &cli.Command{
		Name:  "view",
		Usage: "View widget",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:     "widget-id",
				Usage:    "Unique id of the widget",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := commands.ResolveClient()
			if err != nil {
				return err
			}

			req := api.ViewWidgetRequest{
				WidgetID: cmd.String("widget-id"),
			}

			resp, err := client.ViewWidget(ctx, req)
			if err != nil {
				return fmt.Errorf("viewWidget: %w", err)
			}

			return output.Handle(cmd.Root().Writer, resp)
		},
	}
}

// widgetsCreateCommand returns the "create" command.
func widgetsCreateCommand() *cli.Command {
	return &cli.Command{
		Name:  "create",
		Usage: "Create widget",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "general-color",
				Usage: "The color of the widget",
			},
			&cli.StringFlag{
				Name:     "general-name",
				Usage:    "The name of the widget",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := commands.ResolveClient()
			if err != nil {
				return err
			}

			req := api.CreateWidgetRequest{
				GeneralColor: cmd.String("general-color"),
				GeneralName:  cmd.String("general-name"),
			}

			resp, err := client.CreateWidget(ctx, req)
			if err != nil {
				return fmt.Errorf("createWidget: %w", err)
			}

			return output.Handle(cmd.Root().Writer, resp)
		},
	}
}

// widgetsActivateCommand returns the "activate" command.
func widgetsActivateCommand() *cli.Command {
	return &cli.Command{
		Name:  "activate",
		Usage: "Activate widget",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:     "widget-id",
				Usage:    "Unique id of the widget",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := commands.ResolveClient()
			if err != nil {
				return err
			}

			req := api.ActivateWidgetRequest{
				WidgetID: cmd.String("widget-id"),
			}

			resp, err := client.ActivateWidget(ctx, req)
			if err != nil {
				return fmt.Errorf("activateWidget: %w", err)
			}

			return output.Handle(cmd.Root().Writer, resp)
		},
	}
}
